version: '2'
services:
    db:
        image: ifl19_db
        volumes:
            - ifl19_db:/var/lib/postgresql/data
    links:
        image: ifl19_links
        depends_on:
            - db
        ports:
            - 8080:8080
        command: /home/opam/run-curation.sh
volumes:
    ifl19_db:
        external: true
